### ISSUE TITLE
The creation of the icon paths

### ISSUE THREAD

**Issue by davisb10** [boraunal/Font-Awesome-Adobe-Experience-Design#4]
@boraunal I'm wondering how you created the individual icon paths? They are clear and not pixelated even at 2000% zoom in Adobe XD. 

I'm wanting to do a similar process to a different font library and haven't been able to get them as clear and defined.

**Comment by boraunal** [comment]
Hi Davis, I used SVG files from the font-awesome source. XD has capabilities to use SVG therefore there will be no when zoom-in.

**Comment by davisb10** [comment]
Awesome, thanks! I tried to export the individual svg items from the main svg file of a font library I want to do this on using IcoMoon, but they always come out pixelated. I guess I need to just see if I can get the individual SVG files from the creator of the library.
